name: 🛑Deploy🛑 to Frontend to Prod
'on':
  workflow_dispatch:
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: "Setting up node version."
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASUOYEBOAHSDA }}'
          projectId: asuoyeboahsda
